apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: aily
resources:
  - ../../../base/aily-frontend
images:
  - name: REPLACE_WITH_ECR_AILY_FRONTEND_URL
    newName: REPLACE_WITH_ECR_AILY_FRONTEND_URL
    newTag: latest
