apiVersion: apps/v1
kind: Deployment
metadata:
  name: aily-frontend
  namespace: aily
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aily-frontend
  template:
    metadata:
      labels:
        app: aily-frontend
    spec:
      tolerations:
        - key: workload
          operator: Equal
          value: "true"
          effect: NoSchedule
      containers:
        - name: frontend
          image: REPLACE_WITH_ECR_AILY_FRONTEND_URL
          ports:
            - containerPort: 8501
          env:
            - name: API_URL
              value: http://aily-api.aily.svc.cluster.local
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              memory: 512Mi
