apiVersion: v1
kind: Service
metadata:
  name: aily-frontend
  namespace: aily
spec:
  type: ClusterIP
  selector:
    app: aily-frontend
  ports:
    - port: 80
      targetPort: 8501
      protocol: TCP
