apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: langfuse
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://langfuse.github.io/langfuse-k8s
    chart: langfuse
    targetRevision: "1.*"
    helm:
      valuesObject:
        langfuse:
          salt:
            secretKeyRef:
              name: langfuse-secret
              key: SALT
          nextauth:
            url: "REPLACE_WITH_LANGFUSE_NEXTAUTH_URL"
            secret:
              secretKeyRef:
                name: langfuse-secret
                key: NEXTAUTH_SECRET
          additionalEnv:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: langfuse-secret
                  key: DATABASE_URL
            - name: REDIS_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: langfuse-secret
                  key: REDIS_CONNECTION_STRING
          serviceAccount:
            annotations:
              eks.amazonaws.com/role-arn: REPLACE_WITH_LANGFUSE_IRSA_ARN
        tolerations:
          - key: role
            operator: Equal
            value: workload
            effect: NoSchedule
        nodeSelector:
          role: workload
        postgresql:
          enabled: false
        redis:
          enabled: false
        clickhouse:
          enabled: false
          host: clickhouse-langfuse.clickhouse.svc.cluster.local
          clusterName: langfuse
          auth:
            username: langfuse
            existingSecret: langfuse-secret
            existingSecretKey: CLICKHOUSE_PASSWORD
        s3:
          enabled: false
          region: us-west-2
          bucket: aily-prod-ml-data
          mediaUpload:
            enabled: true
            prefix: langfuse/
  destination:
    server: https://kubernetes.default.svc
    namespace: langfuse
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
