apiVersion: clickhouse.altinity.com/v1
kind: ClickHouseInstallation
metadata:
  name: langfuse
  namespace: clickhouse
spec:
  configuration:
    users:
      langfuse/k8s_secret_password:
        valueFrom:
          secretKeyRef:
            name: clickhouse-secret
            namespace: clickhouse
            key: password
      langfuse/networks/ip: "::/0"
      langfuse/profile: default
    zookeeper:
      nodes:
        - host: localhost
          port: 9181
    files:
      config.d/keeper.xml: |
        <clickhouse>
          <keeper_server>
            <tcp_port>9181</tcp_port>
            <server_id>1</server_id>
            <log_storage_path>/var/lib/clickhouse/coordination/log</log_storage_path>
            <snapshot_storage_path>/var/lib/clickhouse/coordination/snapshots</snapshot_storage_path>
            <raft_configuration>
              <server>
                <id>1</id>
                <hostname>localhost</hostname>
                <port>9234</port>
              </server>
            </raft_configuration>
          </keeper_server>
        </clickhouse>
    clusters:
      - name: langfuse
        layout:
          shardsCount: 1
          replicasCount: 1
  templates:
    podTemplates:
      - name: default
        spec:
          tolerations:
            - key: role
              operator: Equal
              value: clickhouse
              effect: NoSchedule
          nodeSelector:
            role: clickhouse
          containers:
            - name: clickhouse
              image: clickhouse/clickhouse-server:25.5
              resources:
                requests:
                  cpu: "1"
                  memory: 8Gi
                limits:
                  memory: 14Gi
    volumeClaimTemplates:
      - name: default
        spec:
          accessModes:
            - ReadWriteOnce
          storageClassName: gp3
          resources:
            requests:
              storage: 100Gi
