apiVersion: v1
kind: Service
metadata:
  name: aily-api
  namespace: aily
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  type: ClusterIP
  selector:
    app: aily-api
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
