use_default_settings: true

search:
  formats:
    - html
    - json

server:
  secret_key: "local-dev-only-not-for-production"
  limiter: false
  image_proxy: false
  method: GET

botdetection:
  ip_limit:
    enabled: false
  ip_lists:
    enabled: false

engines:
  - name: startpage
    disabled: true
  - name: brave
    disabled: true
