name: ci

on:
  pull_request:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: make build-api
      - run: make lint

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: make build-api
      - run: make format-check

# 開発の妨げになるので一時的に外した。
#  typecheck:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#      - run: make build-api
#      - run: make typecheck
